# action.yml
name: 'Install compatibility layer'
description: 'Use Ansible playbook to install the compatibility layer inside a Gentoo Prefix Docker container'
inputs:
  prefix-path:  
    description: 'Path to the Gentoo Prefix installation'
    required: true
    default: '/tmp/gentoo'
#outputs:
#  time: # id of output
#    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.prefix-path }}
