---
- name: Install package set
  portage:
    package: "{{ pkg_set }}"
    state: present
  tags:
    - set

- name: Install additional packages
  portage:
    package: "{{ item }}"
    state: present
  with_items: "{{ prefix_packages }}"
