# TODO: when startprefix does not exist
# use container to install prefix?
#- include_tasks: install_prefix.yml

- name: Check if a Prefix installation is found at the specified location
  stat:
    path: "{{ prefix_location }}/usr/bin/emerge"
  register: emerge

- name: Start transaction
  command: "cvmfs_server transaction {{ cvmfs_repository }}"
  when: cvmfs_start_transaction

- block:
  - include_tasks: add_overlay.yml
    when: emerge.stat.exists

  - include_tasks: install_packages.yml
    when: emerge.stat.exists

  - name: Publish transaction
    command: "cvmfs_server publish {{ cvmfs_repository }}"
    when: cvmfs_publish_transaction

  rescue:
    - name: Abort transaction
      command: "cvmfs_server abort {{ cvmfs_repository }}"
      when: cvmfs_abort_transaction_on_failures
