---
- name: Converge
  hosts:
    - all
  roles:
    - compatibility-layer
  vars:
    ansible_python_interpreter: /usr/bin/python3
  environment:
    PATH: "{{ gentoo_prefix_path }}/usr/bin:{{ gentoo_prefix_path }}/bin:{{ ansible_env.PATH }}"
    EPREFIX: "{{ gentoo_prefix_path }}"
    BPREFIX: "{{ gentoo_prefix_path }}"
    LC_ALL: C
